version: '3'

services:
  network-creator:
    image: alpine:latest
    command: "true"
    networks:
      - servidor-net

networks:
  servidor-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00::/80