# version: "1.0"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped

    expose:
      - 32400
    network_mode: "host" # Solo funciona en Linux

    environment:
      PUID: ${PLEX_PUID}
      PGID: ${PLEX_PGID}
      TZ: ${PLEX_TZ}
      PLEX_CLAIM: ${PLEX_PLEX_CLAIM}
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
      CHANGE_CONFIG_DIR_OWNERSHIP: ${PLEX_CHANGE_CONFIG_DIR_OWNERSHIP}}

    volumes:
      - ./config:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.rule=Host(`$PLEX_HOST`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

    networks:
      servidor-net:

networks:
  servidor-net:
    external: true
