# version: '1'

services:

  mailserver:
    image: analogic/poste.io
    container_name: postie
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - h=kronos.cloudns.ph # Direccion del servidor de mail hosting
      - DISABLE_CLAMAV=TRUE
      - DISABLE_LETSENCRYPT=TRUE
      - HTTPS=OFF

    volumes:
      - /mnt/mail:/data

    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.mailserver.rule=Host(`kronos.cloudns.ph`)"
      - "traefik.http.routers.mailserver.entrypoints=http"
      - "traefik.http.routers.mailserver.service=mailserver"
      - "traefik.http.routers.mailserver.tls=true"
      - "traefik.http.services.mailserver.loadbalancer.server.port=80"

      # HTTPS
      - "traefik.http.routers.mailserver-secure.entrypoints=https"
      - "traefik.http.routers.mailserver-secure.rule=Host(`kronos.cloudns.ph`)"
      - "traefik.http.routers.mailserver-secure.service=mailserver"
      - "traefik.http.routers.mailserver-secure.tls=true"
      - "traefik.http.services.mailserver-secure.loadbalancer.server.port=443"
      - "traefik.http.routers.mailserver-secure.tls.certresolver=myresolver" # Assuming your Traefik is configured with a certresolver named 'le'

      # Mail ports


      # SMTP

      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.routers.smtp.service=smtp"

#      - "traefik.tcp.routers.smtps.rule=HostSNI(`*`)"
#      - "traefik.tcp.routers.smtps.entrypoints=smtps"
#      - "traefik.tcp.services.smtps.loadbalancer.server.port=465"
#      - "traefik.tcp.routers.smtps.service=smtp"

      - "traefik.tcp.routers.smtpss.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtpss.entrypoints=smtpss"
      - "traefik.tcp.services.smtpss.loadbalancer.server.port=587"
      - "traefik.tcp.routers.smtpss.service=smtp"

      # IMAP

#      - "traefik.tcp.routers.imap.rule=HostSNI(`*`)"
#      - "traefik.tcp.routers.imap.entrypoints=imap"
#      - "traefik.tcp.services.imap.loadbalancer.server.port=143"
#      - "traefik.tcp.routers.imap.service=imap"

      - "traefik.tcp.routers.imaps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imaps.entrypoints=imaps"
      - "traefik.tcp.services.imaps.loadbalancer.server.port=993"
      - "traefik.tcp.routers.imaps.service=imaps"



      # Add similar configurations for other mail ports (587, 993, etc.)

    networks:
      - proxy

#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    ports:
      - "25:25"
#      - "110:110"
#      - "143:143"
#      - "465:465"
      - "587:587"
      - "993:993"
#      - "995:995"

networks:
  proxy:
    external: true
